#!/bin/bash

set -e
set -o pipefail

if [[ "$#" != 1 ]]; then
        echo "Expected usage: $0 <TEST USERNAME>"
        exit 1
fi

TEST_USER="$1"

FETCH_START="$(date +%s)"
sss_cache -u "$TEST_USER"
getent passwd "$TEST_USER" > /dev/null
LAST_UPDATE="$(ldbsearch -H /var/lib/sss/db/cache_LDAP.ldb "(name=$TEST_USER)" 2> /dev/null | grep lastUpdate | sed -e 's/^lastUpdate: //')"

if (( "$FETCH_START" > "$LAST_UPDATE" )); then
        echo "sssd is offline" >&2
        exit 2
fi

